[package]
name = "lunarpay"
version = "0.0.1"
authors = [ "contact@esdt.space",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.multiversx-sc]
version = "0.50.1"

[dev-dependencies.multiversx-sc-scenario]
version = "0.50.1"
