[package]
name = "lunarpay-meta"
version = "0.0.1"
edition = "2021"
publish = false
authors = [ "contact@esdt.space",]

[dev-dependencies]

[dependencies.lunarpay]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.3"
